name: Publish

on: push

jobs:
  publish:
    name: Publish latest version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Give Docker image write access to the repo
        run: chmod -R o+w .
      - name: Build with Inform 7
        run: make
      - name: Debug - WIP
        run: |
          ls -la MoonShot.materials/; ls -la MoonShot.materials/Release/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MoonShot.materials/Release/

