name: Publish

on: push

jobs:
  publish:
    name: Publish latest version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Debug - WIP
        run: |
          docker run \
            --mount type=bind,source="$(pwd)",target=/home/informer \
            katre/docker-inform \
            /bin/bash -c '/bin/ls -la; whoami; pwd'
      - name: Build with Inform 7
        run: make
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MoonShot.materials/Release/

